import asyncio
from redis import asyncio as aioredis
from navigator_session.storages.redis import RedisStorage
from navigator_session import SESSION_KEY

async def test():
    conn = aioredis.Redis.from_url('redis://localhost')
    storage = RedisStorage()
    
    # 1. Create a dummy ghost session payload just like the ones failing
    # Ghost sessions generated by auth_middleware look like this:
    ghost_data = {
        'session_id': 'ghost_123',
        'created': 1771981595.0,
        'last_visit': 1771981595.0,
        SESSION_KEY: None  # The identity is None
    }
    encoded = storage._encoder(ghost_data)
    await conn.set('session:ghost_123', encoded)
    
    # 2. Retrieve it
    raw = await conn.get('session:ghost_123')
    decoded = storage._decoder(raw)
    
    print("====== EMPTY SESSION ======")
    print(decoded)
    
    # Let's test our validation condition:
    is_invalid = not decoded or list(decoded.keys()) == ['session_id'] or not decoded.get(SESSION_KEY)
    print("Is Invalid? ", is_invalid)
    
    await conn.delete('session:ghost_123')
    await conn.close()

asyncio.run(test())
